camera/horizontal_fov: 360.0
camera/vertical_fov: 30.0

raycast/dr:     0.1
raycast/dphi:   10
raycast/dtheta: 10

system/bbx/r: 0.65
system/bbx/overshoot: 0.1

aep/gain/r_min: 0
aep/gain/r_max: 10
aep/gain/zero: 1
aep/gain/lambda: 0.15
aep/gain/sigma_thresh: 0.2
aep/tree/extension_range: 1
aep/tree/max_sampling_radius: 10
aep/tree/initial_iterations: 25
aep/tree/cutoff_iterations: 50

rrt/min_nodes: 100

# bounding box: necessary to limit the simulation 
# scenario (smaller than actual gazebo scenario)
# boundary/min: [-9, -5, 0.0]
# boundary/max: [9, 5.0, 1.5]
# boundary/min: [-8.5, -10, 0.0]
# boundary/max: [11.5, 10.0, 2.0]
boundary/min: [-14, -14, 0.0]
boundary/max: [14, 14, 2.0]

visualize_rays: false
visualize_tree: true
visualize_exploration_area: true

robot_frame: "fcu"
world_frame: "world"

